version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres_data_base
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DATABASE=lesson
    command: postgres
    restart: always
  
  redis:
    image: redis:alpine3.20
    container_name: redis_cache_server
    ports:
      - "6379:6379"